public class TryCatchExample {
    public static void main(String[] args) {
        try {
            int[] numbers = {1, 2, 3, 4, 5};
            
            // Attempt to access an element that is out of bounds
            int result = numbers[10];
            
            // This line will not be executed if an exception occurs
            System.out.println("Result: " + result);
        } catch (ArrayIndexOutOfBoundsException e) {
            // Catch and handle the ArrayIndexOutOfBoundsException
            System.out.println("An exception occurred: " + e.getMessage());
        }
        
        // This line will be executed regardless of whether an exception occurred
        System.out.println("Program continues...");
    }
}
